In [1]:
# Importamos librer√≠as necesarias
import pandas as pd
import numpy as np
import os
import glob

In [2]:
from funcionesEDA import *

In [3]:
csv_files = glob.glob('*.csv')
lista_data_csv = []
  
# Creamos un bucle que recorre cada archivo csv de la carpeta, crea un df y lo agrega a una lista
for filename in csv_files:
    data = pd.read_csv(filename, encoding='utf-8')
    lista_data_csv.append(data)

In [4]:
# Diccionario que contiene cada df y le asigna como key el nombre del archivo correspondiente
dicc_df = {'price':lista_data_csv[0], 'pricepersqft':lista_data_csv[1]}

In [5]:
for key in dicc_df:
    print(key,'\n\n',dicc_df[key].head(5),'\n\n')

price

    City Code          City         Metro        County State  Population Rank  \
0       6181      New York      New York        Queens    NY                1
1      12447   Los Angeles   Los Angeles   Los Angeles    CA                2
2      17426       Chicago       Chicago          Cook    IL                3
3      39051       Houston       Houston        Harris    TX                4
4      13271  Philadelphia  Philadelphia  Philadelphia    PA                5

   November 2010  December 2010  January 2011  February 2011  ...  April 2016  \
0            NaN            NaN           NaN            NaN  ...        2334
1         2184.0         2184.0        2183.0         2188.0  ...        2637
2         1563.0         1555.0        1547.0         1537.0  ...        1684
3         1198.0         1199.0        1199.0         1200.0  ...        1444
4         1092.0         1099.0        1094.0         1087.0  ...        1206

   May 2016  June 2016  July 2016  August 2016  September 2016  October 2016  \
0      2339       2345       2344         2336            2324          2318
1      2662       2687       2704         2716            2723          2731
2      1686       1687       1685         1681            1675          1668
3      1446       1446       1443         1440            1438          1437
4      1211       1218       1222         1223            1220          1216

   November 2016  December 2016  January 2017
0           2321           2321          2322
1           2740           2748          2753
2           1656           1644          1632
3           1437           1435          1430
4           1211           1209          1212

[5 rows x 81 columns]


pricepersqft

    City Code          City         Metro        County State  Population Rank  \
0       6181      New York      New York        Queens    NY                1
1      12447   Los Angeles   Los Angeles   Los Angeles    CA                2
2      17426       Chicago       Chicago          Cook    IL                3
3      39051       Houston       Houston        Harris    TX                4
4      13271  Philadelphia  Philadelphia  Philadelphia    PA                5

   November 2010  December 2010  January 2011  February 2011  ...  April 2016  \
0            NaN            NaN           NaN            NaN  ...       1.806
1          1.578          1.578         1.580          1.582  ...       1.990
2          1.244          1.248         1.254          1.254  ...       1.354
3          0.788          0.784         0.784          0.786  ...       0.984
4          0.854          0.858         0.858          0.858  ...       0.948

   May 2016  June 2016  July 2016  August 2016  September 2016  October 2016  \
0     1.810      1.816      1.824        1.828           1.836         1.844
1     2.004      2.018      2.026        2.032           2.038         2.042
2     1.362      1.370      1.374        1.378           1.380         1.380
3     0.984      0.982      0.980        0.976           0.974         0.974
4     0.956      0.962      0.964        0.964           0.966         0.968

   November 2016  December 2016  January 2017
0          1.858          1.866         1.872
1          2.048          2.056         2.064
2          1.380          1.376         1.374
3          0.976          0.976         0.974
4          0.972          0.974         0.974

[5 rows x 81 columns]

In [6]:
for key in dicc_df:
    print(key,'\n\n',dicc_df[key].info(),'\n\n')

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13131 entries, 0 to 13130
Data columns (total 81 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   City Code        13131 non-null  int64
 1   City             13131 non-null  object
 2   Metro            11899 non-null  object
 3   County           13131 non-null  object
 4   State            13131 non-null  object
 5   Population Rank  13131 non-null  int64
 6   November 2010    11348 non-null  float64
 7   December 2010    11348 non-null  float64
 8   January 2011     11348 non-null  float64
 9   February 2011    11500 non-null  float64
 10  March 2011       11673 non-null  float64
 11  April 2011       11722 non-null  float64
 12  May 2011         11732 non-null  float64
 13  June 2011        11732 non-null  float64
 14  July 2011        11732 non-null  float64
 15  August 2011      11732 non-null  float64
 16  September 2011   11734 non-null  float64
 17  October 2011     11748 non-null  float64
 18  November 2011    11748 non-null  float64
 19  December 2011    11969 non-null  float64
 20  January 2012     11969 non-null  float64
 21  February 2012    11969 non-null  float64
 22  March 2012       11969 non-null  float64
 23  April 2012       13131 non-null  int64
 24  May 2012         13131 non-null  int64
 25  June 2012        13131 non-null  int64
 26  July 2012        13131 non-null  int64
 27  August 2012      13131 non-null  int64
 28  September 2012   13131 non-null  int64
 29  October 2012     13131 non-null  int64
 30  November 2012    13131 non-null  int64
 31  December 2012    13131 non-null  int64
 32  January 2013     13131 non-null  int64
 33  February 2013    13131 non-null  int64
 34  March 2013       13131 non-null  int64
 35  April 2013       13131 non-null  int64
 36  May 2013         13131 non-null  int64
 37  June 2013        13131 non-null  int64
 38  July 2013        13131 non-null  int64
 39  August 2013      13131 non-null  int64
 40  September 2013   13131 non-null  int64
 41  October 2013     13131 non-null  int64
 42  November 2013    13131 non-null  int64
 43  December 2013    13131 non-null  int64
 44  January 2014     13131 non-null  int64
 45  February 2014    13131 non-null  int64
 46  March 2014       13131 non-null  int64
 47  April 2014       13131 non-null  int64
 48  May 2014         13131 non-null  int64
 49  June 2014        13131 non-null  int64
 50  July 2014        13131 non-null  int64
 51  August 2014      13131 non-null  int64
 52  September 2014   13131 non-null  int64
 53  October 2014     13131 non-null  int64
 54  November 2014    13131 non-null  int64
 55  December 2014    13131 non-null  int64
 56  January 2015     13131 non-null  int64
 57  February 2015    13131 non-null  int64
 58  March 2015       13131 non-null  int64
 59  April 2015       13131 non-null  int64
 60  May 2015         13131 non-null  int64
 61  June 2015        13131 non-null  int64
 62  July 2015        13131 non-null  int64
 63  August 2015      13131 non-null  int64
 64  September 2015   13131 non-null  int64
 65  October 2015     13131 non-null  int64
 66  November 2015    13131 non-null  int64
 67  December 2015    13131 non-null  int64
 68  January 2016     13131 non-null  int64
 69  February 2016    13131 non-null  int64
 70  March 2016       13131 non-null  int64
 71  April 2016       13131 non-null  int64
 72  May 2016         13131 non-null  int64
 73  June 2016        13131 non-null  int64
 74  July 2016        13131 non-null  int64
 75  August 2016      13131 non-null  int64
 76  September 2016   13131 non-null  int64
 77  October 2016     13131 non-null  int64
 78  November 2016    13131 non-null  int64
 79  December 2016    13131 non-null  int64
 80  January 2017     13131 non-null  int64
dtypes: float64(17), int64(60), object(4)
memory usage: 8.1+ MB
price

 None


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11919 entries, 0 to 11918
Data columns (total 81 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   City Code        11919 non-null  int64
 1   City             11919 non-null  object
 2   Metro            11003 non-null  object
 3   County           11919 non-null  object
 4   State            11919 non-null  object
 5   Population Rank  11919 non-null  int64
 6   November 2010    10600 non-null  float64
 7   December 2010    10600 non-null  float64
 8   January 2011     10600 non-null  float64
 9   February 2011    10744 non-null  float64
 10  March 2011       10829 non-null  float64
 11  April 2011       10878 non-null  float64
 12  May 2011         10885 non-null  float64
 13  June 2011        10885 non-null  float64
 14  July 2011        10885 non-null  float64
 15  August 2011      10885 non-null  float64
 16  September 2011   10886 non-null  float64
 17  October 2011     10900 non-null  float64
 18  November 2011    10900 non-null  float64
 19  December 2011    11120 non-null  float64
 20  January 2012     11120 non-null  float64
 21  February 2012    11120 non-null  float64
 22  March 2012       11120 non-null  float64
 23  April 2012       11919 non-null  float64
 24  May 2012         11919 non-null  float64
 25  June 2012        11919 non-null  float64
 26  July 2012        11919 non-null  float64
 27  August 2012      11919 non-null  float64
 28  September 2012   11919 non-null  float64
 29  October 2012     11919 non-null  float64
 30  November 2012    11919 non-null  float64
 31  December 2012    11919 non-null  float64
 32  January 2013     11919 non-null  float64
 33  February 2013    11919 non-null  float64
 34  March 2013       11919 non-null  float64
 35  April 2013       11919 non-null  float64
 36  May 2013         11919 non-null  float64
 37  June 2013        11919 non-null  float64
 38  July 2013        11919 non-null  float64
 39  August 2013      11919 non-null  float64
 40  September 2013   11919 non-null  float64
 41  October 2013     11919 non-null  float64
 42  November 2013    11919 non-null  float64
 43  December 2013    11919 non-null  float64
 44  January 2014     11919 non-null  float64
 45  February 2014    11919 non-null  float64
 46  March 2014       11919 non-null  float64
 47  April 2014       11919 non-null  float64
 48  May 2014         11919 non-null  float64
 49  June 2014        11919 non-null  float64
 50  July 2014        11919 non-null  float64
 51  August 2014      11919 non-null  float64
 52  September 2014   11919 non-null  float64
 53  October 2014     11919 non-null  float64
 54  November 2014    11919 non-null  float64
 55  December 2014    11919 non-null  float64
 56  January 2015     11919 non-null  float64
 57  February 2015    11919 non-null  float64
 58  March 2015       11919 non-null  float64
 59  April 2015       11919 non-null  float64
 60  May 2015         11919 non-null  float64
 61  June 2015        11919 non-null  float64
 62  July 2015        11919 non-null  float64
 63  August 2015      11919 non-null  float64
 64  September 2015   11919 non-null  float64
 65  October 2015     11919 non-null  float64
 66  November 2015    11919 non-null  float64
 67  December 2015    11919 non-null  float64
 68  January 2016     11919 non-null  float64
 69  February 2016    11919 non-null  float64
 70  March 2016       11919 non-null  float64
 71  April 2016       11919 non-null  float64
 72  May 2016         11919 non-null  float64
 73  June 2016        11919 non-null  float64
 74  July 2016        11919 non-null  float64
 75  August 2016      11919 non-null  float64
 76  September 2016   11919 non-null  float64
 77  October 2016     11919 non-null  float64
 78  November 2016    11919 non-null  float64
 79  December 2016    11919 non-null  float64
 80  January 2017     11919 non-null  float64
dtypes: float64(75), int64(2), object(4)
memory usage: 7.4+ MB
pricepersqft

 None

In [7]:
for key in dicc_df:
    print(key,'\n\n',dicc_df[key].describe(exclude=np.number),'\n\n')

price

            City     Metro     County  State
count     13131     11899      13131  13131
unique     9670       701       1227     51
top     Clinton  New York  Jefferson     PA
freq         18       595        197   1260


pricepersqft

            City     Metro      County  State
count     11919     11003       11919  11919
unique     8971       678        1147     51
top     Clinton  New York  Montgomery     PA
freq         17       583         188   1114

In [8]:
for key in dicc_df:
    print(key,'\n\n',dicc_df[key].describe(exclude=object),'\n\n')

price

            City Code  Population Rank  November 2010  December 2010  \
count   13131.000000     13131.000000   11348.000000   11348.000000
mean    78126.756454      6566.000000    1327.100458    1331.831953
std    119604.910806      3790.737527     652.531343     655.822002
min      3300.000000         1.000000     547.000000     539.000000
25%     18803.000000      3283.500000     982.000000     984.750000
50%     34678.000000      6566.000000    1195.000000    1199.000000
75%     51385.500000      9848.500000    1479.000000    1479.000000
max    737791.000000     13131.000000   18787.000000   18848.000000

       January 2011  February 2011    March 2011    April 2011      May 2011  \
count  11348.000000   11500.000000  11673.000000  11722.000000  11732.000000
mean    1334.447744    1331.935217   1327.595819   1323.824518   1321.730822
std      653.931315     647.853483    640.168818    636.392831    633.675563
min      536.000000     542.000000    535.000000    533.000000    533.000000
25%      986.000000     984.000000    979.000000    973.000000    971.000000
50%     1201.500000    1201.000000   1201.000000   1196.000000   1194.000000
75%     1479.000000    1477.000000   1473.000000   1471.000000   1472.000000
max    19054.000000   19019.000000  18997.000000  18939.000000  19119.000000

          June 2011  ...    April 2016      May 2016     June 2016  \
count  11732.000000  ...  13131.000000  13131.000000  13131.000000
mean    1321.872826  ...   1466.406519   1470.625695   1472.876856
std      631.981504  ...    813.253498    815.322324    819.417181
min      536.000000  ...    543.000000    548.000000    547.000000
25%      972.000000  ...   1041.000000   1044.000000   1046.000000
50%     1193.000000  ...   1275.000000   1277.000000   1278.000000
75%     1473.000000  ...   1625.000000   1630.000000   1633.000000
max    19442.000000  ...  21344.000000  20547.000000  20400.000000

          July 2016   August 2016  September 2016  October 2016  \
count  13131.000000  13131.000000    13131.000000  13131.000000
mean    1471.627370   1468.666667     1465.817988   1465.572157
std      823.317848    825.885842      826.421670    825.621199
min      544.000000    539.000000      532.000000    527.000000
25%     1043.500000   1038.000000     1034.000000   1032.000000
50%     1276.000000   1270.000000     1268.000000   1266.000000
75%     1629.000000   1628.000000     1628.000000   1630.500000
max    20639.000000  20695.000000    20615.000000  20163.000000

       November 2016  December 2016  January 2017
count   13131.000000   13131.000000  13131.000000
mean     1467.105247    1467.524636   1467.296550
std       824.678612     821.891626    820.707579
min       518.000000     517.000000    518.000000
25%      1033.000000    1034.000000   1035.000000
50%      1267.000000    1267.000000   1264.000000
75%      1630.000000    1632.000000   1634.000000
max     19460.000000   18605.000000  17985.000000

[8 rows x 77 columns]


pricepersqft

            City Code  Population Rank  November 2010  December 2010  \
count   11919.000000     11919.000000   10600.000000   10600.000000
mean    77097.011998      5960.000000       0.860989       0.863896
std    118093.323482      3440.863264       0.286088       0.286489
min      3300.000000         1.000000       0.360000       0.358000
25%     18762.000000      2980.500000       0.676000       0.678000
50%     34637.000000      5960.000000       0.796000       0.799000
75%     51298.500000      8939.500000       0.972000       0.974000
max    737791.000000     11919.000000       4.482000       4.508000

       January 2011  February 2011    March 2011    April 2011      May 2011  \
count  10600.000000   10744.000000  10829.000000  10878.000000  10885.000000
mean       0.865602       0.864939      0.862232      0.860946      0.859769
std        0.284910       0.281532      0.278903      0.277075      0.275870
min        0.358000       0.358000      0.362000      0.366000      0.366000
25%        0.680000       0.682000      0.680000      0.678000      0.678000
50%        0.802000       0.802000      0.800000      0.800000      0.798000
75%        0.976000       0.972000      0.970000      0.968000      0.968000
max        4.558000       4.564000      4.548000      4.536000      4.528000

          June 2011  ...    April 2016      May 2016     June 2016  \
count  10885.000000  ...  11919.000000  11919.000000  11919.000000
mean       0.859848  ...      0.958509      0.962608      0.964971
std        0.275311  ...      0.371177      0.373848      0.376643
min        0.366000  ...      0.394000      0.392000      0.388000
25%        0.678000  ...      0.732000      0.734000      0.734000
50%        0.800000  ...      0.870000      0.872000      0.872000
75%        0.968000  ...      1.072000      1.076000      1.080000
max        4.536000  ...      6.252000      6.342000      6.404000

          July 2016   August 2016  September 2016  October 2016  \
count  11919.000000  11919.000000    11919.000000  11919.000000
mean       0.964989      0.963645        0.962379      0.962570
std        0.378865      0.380334        0.381100      0.381545
min        0.384000      0.382000        0.378000      0.378000
25%        0.732000      0.730000        0.728000      0.728000
50%        0.872000      0.870000        0.870000      0.870000
75%        1.082000      1.080000        1.080000      1.082000
max        6.452000      6.476000        6.486000      6.476000

       November 2016  December 2016  January 2017
count   11919.000000   11919.000000  11919.000000
mean        0.963743       0.964275      0.964356
std         0.381775       0.381395      0.381297
min         0.378000       0.378000      0.378000
25%         0.728000       0.730000      0.732000
50%         0.870000       0.872000      0.872000
75%         1.082000       1.080000      1.080000
max         6.470000       6.440000      6.406000

[8 rows x 77 columns]

## - Valores Nulos

In [9]:
valores_faltantes(dicc_df)

price

City Code 	 0.0 %
City 	 0.0 %
Metro 	 9.38 %
County 	 0.0 %
State 	 0.0 %
Population Rank 	 0.0 %
November 2010 	 13.58 %
December 2010 	 13.58 %
January 2011 	 13.58 %
February 2011 	 12.42 %
March 2011 	 11.1 %
April 2011 	 10.73 %
May 2011 	 10.65 %
June 2011 	 10.65 %
July 2011 	 10.65 %
August 2011 	 10.65 %
September 2011 	 10.64 %
October 2011 	 10.53 %
November 2011 	 10.53 %
December 2011 	 8.85 %
January 2012 	 8.85 %
February 2012 	 8.85 %
March 2012 	 8.85 %
April 2012 	 0.0 %
May 2012 	 0.0 %
June 2012 	 0.0 %
July 2012 	 0.0 %
August 2012 	 0.0 %
September 2012 	 0.0 %
October 2012 	 0.0 %
November 2012 	 0.0 %
December 2012 	 0.0 %
January 2013 	 0.0 %
February 2013 	 0.0 %
March 2013 	 0.0 %
April 2013 	 0.0 %
May 2013 	 0.0 %
June 2013 	 0.0 %
July 2013 	 0.0 %
August 2013 	 0.0 %
September 2013 	 0.0 %
October 2013 	 0.0 %
November 2013 	 0.0 %
December 2013 	 0.0 %
January 2014 	 0.0 %
February 2014 	 0.0 %
March 2014 	 0.0 %
April 2014 	 0.0 %
May 2014 	 0.0 %
June 2014 	 0.0 %
July 2014 	 0.0 %
August 2014 	 0.0 %
September 2014 	 0.0 %
October 2014 	 0.0 %
November 2014 	 0.0 %
December 2014 	 0.0 %
January 2015 	 0.0 %
February 2015 	 0.0 %
March 2015 	 0.0 %
April 2015 	 0.0 %
May 2015 	 0.0 %
June 2015 	 0.0 %
July 2015 	 0.0 %
August 2015 	 0.0 %
September 2015 	 0.0 %
October 2015 	 0.0 %
November 2015 	 0.0 %
December 2015 	 0.0 %
January 2016 	 0.0 %
February 2016 	 0.0 %
March 2016 	 0.0 %
April 2016 	 0.0 %
May 2016 	 0.0 %
June 2016 	 0.0 %
July 2016 	 0.0 %
August 2016 	 0.0 %
September 2016 	 0.0 %
October 2016 	 0.0 %
November 2016 	 0.0 %
December 2016 	 0.0 %
January 2017 	 0.0 %



pricepersqft

City Code 	 0.0 %
City 	 0.0 %
Metro 	 7.69 %
County 	 0.0 %
State 	 0.0 %
Population Rank 	 0.0 %
November 2010 	 11.07 %
December 2010 	 11.07 %
January 2011 	 11.07 %
February 2011 	 9.86 %
March 2011 	 9.15 %
April 2011 	 8.73 %
May 2011 	 8.68 %
June 2011 	 8.68 %
July 2011 	 8.68 %
August 2011 	 8.68 %
September 2011 	 8.67 %
October 2011 	 8.55 %
November 2011 	 8.55 %
December 2011 	 6.7 %
January 2012 	 6.7 %
February 2012 	 6.7 %
March 2012 	 6.7 %
April 2012 	 0.0 %
May 2012 	 0.0 %
June 2012 	 0.0 %
July 2012 	 0.0 %
August 2012 	 0.0 %
September 2012 	 0.0 %
October 2012 	 0.0 %
November 2012 	 0.0 %
December 2012 	 0.0 %
January 2013 	 0.0 %
February 2013 	 0.0 %
March 2013 	 0.0 %
April 2013 	 0.0 %
May 2013 	 0.0 %
June 2013 	 0.0 %
July 2013 	 0.0 %
August 2013 	 0.0 %
September 2013 	 0.0 %
October 2013 	 0.0 %
November 2013 	 0.0 %
December 2013 	 0.0 %
January 2014 	 0.0 %
February 2014 	 0.0 %
March 2014 	 0.0 %
April 2014 	 0.0 %
May 2014 	 0.0 %
June 2014 	 0.0 %
July 2014 	 0.0 %
August 2014 	 0.0 %
September 2014 	 0.0 %
October 2014 	 0.0 %
November 2014 	 0.0 %
December 2014 	 0.0 %
January 2015 	 0.0 %
February 2015 	 0.0 %
March 2015 	 0.0 %
April 2015 	 0.0 %
May 2015 	 0.0 %
June 2015 	 0.0 %
July 2015 	 0.0 %
August 2015 	 0.0 %
September 2015 	 0.0 %
October 2015 	 0.0 %
November 2015 	 0.0 %
December 2015 	 0.0 %
January 2016 	 0.0 %
February 2016 	 0.0 %
March 2016 	 0.0 %
April 2016 	 0.0 %
May 2016 	 0.0 %
June 2016 	 0.0 %
July 2016 	 0.0 %
August 2016 	 0.0 %
September 2016 	 0.0 %
October 2016 	 0.0 %
November 2016 	 0.0 %
December 2016 	 0.0 %
January 2017 	 0.0 %

## -- Registros Duplicados

In [10]:
registros_duplicados(dicc_df)

price : 0
pricepersqft : 0

## -- Outliers

In [11]:
cantidad_outliers(dicc_df)

price
City Code
Q1:  18803.0
Q3:  51385.5
IQR:  32582.5
BI:  -30070.75
BS:  100259.25
Hay 2079 valores at√≠picos en la variable City Code


price
November 2010
Q1:  982.0
Q3:  1479.0
IQR:  497.0
BI:  236.5
BS:  2224.5
Hay 622 valores at√≠picos en la variable November 2010


price
December 2010
Q1:  984.75
Q3:  1479.0
IQR:  494.25
BI:  243.375
BS:  2220.375
Hay 637 valores at√≠picos en la variable December 2010


price
January 2011
Q1:  986.0
Q3:  1479.0
IQR:  493.0
BI:  246.5
BS:  2218.5
Hay 634 valores at√≠picos en la variable January 2011


price
February 2011
Q1:  984.0
Q3:  1477.0
IQR:  493.0
BI:  244.5
BS:  2216.5
Hay 645 valores at√≠picos en la variable February 2011


price
March 2011
Q1:  979.0
Q3:  1473.0
IQR:  494.0
BI:  238.0
BS:  2214.0
Hay 639 valores at√≠picos en la variable March 2011


price
April 2011
Q1:  973.0
Q3:  1471.0
IQR:  498.0
BI:  226.0
BS:  2218.0
Hay 628 valores at√≠picos en la variable April 2011


price
May 2011
Q1:  971.0
Q3:  1472.0
IQR:  501.0
BI:  219.5
BS:  2223.5
Hay 628 valores at√≠picos en la variable May 2011


price
June 2011
Q1:  972.0
Q3:  1473.0
IQR:  501.0
BI:  220.5
BS:  2224.5
Hay 625 valores at√≠picos en la variable June 2011


price
July 2011
Q1:  974.0
Q3:  1473.0
IQR:  499.0
BI:  225.5
BS:  2221.5
Hay 619 valores at√≠picos en la variable July 2011


price
August 2011
Q1:  973.0
Q3:  1470.0
IQR:  497.0
BI:  227.5
BS:  2215.5
Hay 616 valores at√≠picos en la variable August 2011


price
September 2011
Q1:  971.0
Q3:  1464.0
IQR:  493.0
BI:  231.5
BS:  2203.5
Hay 627 valores at√≠picos en la variable September 2011


price
October 2011
Q1:  962.0
Q3:  1461.0
IQR:  499.0
BI:  213.5
BS:  2209.5
Hay 626 valores at√≠picos en la variable October 2011


price
November 2011
Q1:  957.0
Q3:  1459.0
IQR:  502.0
BI:  204.0
BS:  2212.0
Hay 630 valores at√≠picos en la variable November 2011


price
December 2011
Q1:  955.0
Q3:  1480.0
IQR:  525.0
BI:  167.5
BS:  2267.5
Hay 703 valores at√≠picos en la variable December 2011


price
January 2012
Q1:  954.0
Q3:  1482.0
IQR:  528.0
BI:  162.0
BS:  2274.0
Hay 689 valores at√≠picos en la variable January 2012


price
February 2012
Q1:  955.0
Q3:  1484.0
IQR:  529.0
BI:  161.5
BS:  2277.5
Hay 688 valores at√≠picos en la variable February 2012


price
March 2012
Q1:  958.0
Q3:  1488.0
IQR:  530.0
BI:  163.0
BS:  2283.0
Hay 680 valores at√≠picos en la variable March 2012


price
April 2012
Q1:  961.0
Q3:  1468.0
IQR:  507.0
BI:  200.5
BS:  2228.5
Hay 758 valores at√≠picos en la variable April 2012


price
May 2012
Q1:  962.0
Q3:  1473.0
IQR:  511.0
BI:  195.5
BS:  2239.5
Hay 755 valores at√≠picos en la variable May 2012


price
June 2012
Q1:  960.0
Q3:  1475.0
IQR:  515.0
BI:  187.5
BS:  2247.5
Hay 757 valores at√≠picos en la variable June 2012


price
July 2012
Q1:  956.0
Q3:  1476.5
IQR:  520.5
BI:  175.25
BS:  2257.25
Hay 745 valores at√≠picos en la variable July 2012


price
August 2012
Q1:  955.0
Q3:  1475.0
IQR:  520.0
BI:  175.0
BS:  2255.0
Hay 752 valores at√≠picos en la variable August 2012


price
September 2012
Q1:  955.0
Q3:  1473.0
IQR:  518.0
BI:  178.0
BS:  2250.0
Hay 759 valores at√≠picos en la variable September 2012


price
October 2012
Q1:  958.0
Q3:  1471.0
IQR:  513.0
BI:  188.5
BS:  2240.5
Hay 760 valores at√≠picos en la variable October 2012


price
November 2012
Q1:  962.0
Q3:  1472.0
IQR:  510.0
BI:  197.0
BS:  2237.0
Hay 767 valores at√≠picos en la variable November 2012


price
December 2012
Q1:  963.5
Q3:  1475.0
IQR:  511.5
BI:  196.25
BS:  2242.25
Hay 756 valores at√≠picos en la variable December 2012


price
January 2013
Q1:  963.0
Q3:  1478.0
IQR:  515.0
BI:  190.5
BS:  2250.5
Hay 767 valores at√≠picos en la variable January 2013


price
February 2013
Q1:  961.0
Q3:  1486.0
IQR:  525.0
BI:  173.5
BS:  2273.5
Hay 742 valores at√≠picos en la variable February 2013


price
March 2013
Q1:  957.0
Q3:  1490.0
IQR:  533.0
BI:  157.5
BS:  2289.5
Hay 740 valores at√≠picos en la variable March 2013


price
April 2013
Q1:  959.0
Q3:  1492.5
IQR:  533.5
BI:  158.75
BS:  2292.75
Hay 741 valores at√≠picos en la variable April 2013


price
May 2013
Q1:  960.0
Q3:  1494.5
IQR:  534.5
BI:  158.25
BS:  2296.25
Hay 745 valores at√≠picos en la variable May 2013


price
June 2013
Q1:  963.0
Q3:  1496.0
IQR:  533.0
BI:  163.5
BS:  2295.5
Hay 751 valores at√≠picos en la variable June 2013


price
July 2013
Q1:  968.0
Q3:  1497.0
IQR:  529.0
BI:  174.5
BS:  2290.5
Hay 768 valores at√≠picos en la variable July 2013


price
August 2013
Q1:  970.0
Q3:  1497.0
IQR:  527.0
BI:  179.5
BS:  2287.5
Hay 785 valores at√≠picos en la variable August 2013


price
September 2013
Q1:  974.0
Q3:  1500.0
IQR:  526.0
BI:  185.0
BS:  2289.0
Hay 798 valores at√≠picos en la variable September 2013


price
October 2013
Q1:  979.0
Q3:  1506.0
IQR:  527.0
BI:  188.5
BS:  2296.5
Hay 799 valores at√≠picos en la variable October 2013


price
November 2013
Q1:  984.5
Q3:  1512.0
IQR:  527.5
BI:  193.25
BS:  2303.25
Hay 797 valores at√≠picos en la variable November 2013


price
December 2013
Q1:  987.0
Q3:  1515.0
IQR:  528.0
BI:  195.0
BS:  2307.0
Hay 791 valores at√≠picos en la variable December 2013


price
January 2014
Q1:  984.0
Q3:  1516.0
IQR:  532.0
BI:  186.0
BS:  2314.0
Hay 772 valores at√≠picos en la variable January 2014


price
February 2014
Q1:  981.5
Q3:  1515.0
IQR:  533.5
BI:  181.25
BS:  2315.25
Hay 774 valores at√≠picos en la variable February 2014


price
March 2014
Q1:  977.0
Q3:  1512.5
IQR:  535.5
BI:  173.75
BS:  2315.75
Hay 779 valores at√≠picos en la variable March 2014


price
April 2014
Q1:  976.0
Q3:  1510.5
IQR:  534.5
BI:  174.25
BS:  2312.25
Hay 789 valores at√≠picos en la variable April 2014


price
May 2014
Q1:  969.0
Q3:  1507.0
IQR:  538.0
BI:  162.0
BS:  2314.0
Hay 797 valores at√≠picos en la variable May 2014


price
June 2014
Q1:  965.0
Q3:  1504.0
IQR:  539.0
BI:  156.5
BS:  2312.5
Hay 802 valores at√≠picos en la variable June 2014


price
July 2014
Q1:  963.0
Q3:  1507.0
IQR:  544.0
BI:  147.0
BS:  2323.0
Hay 793 valores at√≠picos en la variable July 2014


price
August 2014
Q1:  968.0
Q3:  1514.0
IQR:  546.0
BI:  149.0
BS:  2333.0
Hay 801 valores at√≠picos en la variable August 2014


price
September 2014
Q1:  978.0
Q3:  1526.0
IQR:  548.0
BI:  156.0
BS:  2348.0
Hay 809 valores at√≠picos en la variable September 2014


price
October 2014
Q1:  987.0
Q3:  1535.0
IQR:  548.0
BI:  165.0
BS:  2357.0
Hay 818 valores at√≠picos en la variable October 2014


price
November 2014
Q1:  995.0
Q3:  1545.0
IQR:  550.0
BI:  170.0
BS:  2370.0
Hay 824 valores at√≠picos en la variable November 2014


price
December 2014
Q1:  1000.0
Q3:  1552.5
IQR:  552.5
BI:  171.25
BS:  2381.25
Hay 816 valores at√≠picos en la variable December 2014


price
January 2015
Q1:  1004.0
Q3:  1559.0
IQR:  555.0
BI:  171.5
BS:  2391.5
Hay 819 valores at√≠picos en la variable January 2015


price
February 2015
Q1:  1006.0
Q3:  1561.0
IQR:  555.0
BI:  173.5
BS:  2393.5
Hay 830 valores at√≠picos en la variable February 2015


price
March 2015
Q1:  1008.0
Q3:  1565.0
IQR:  557.0
BI:  172.5
BS:  2400.5
Hay 831 valores at√≠picos en la variable March 2015


price
April 2015
Q1:  1012.0
Q3:  1571.0
IQR:  559.0
BI:  173.5
BS:  2409.5
Hay 834 valores at√≠picos en la variable April 2015


price
May 2015
Q1:  1019.0
Q3:  1577.5
IQR:  558.5
BI:  181.25
BS:  2415.25
Hay 848 valores at√≠picos en la variable May 2015


price
June 2015
Q1:  1028.0
Q3:  1586.0
IQR:  558.0
BI:  191.0
BS:  2423.0
Hay 853 valores at√≠picos en la variable June 2015


price
July 2015
Q1:  1035.0
Q3:  1595.0
IQR:  560.0
BI:  195.0
BS:  2435.0
Hay 838 valores at√≠picos en la variable July 2015


price
August 2015
Q1:  1036.0
Q3:  1599.0
IQR:  563.0
BI:  191.5
BS:  2443.5
Hay 829 valores at√≠picos en la variable August 2015


price
September 2015
Q1:  1033.0
Q3:  1602.0
IQR:  569.0
BI:  179.5
BS:  2455.5
Hay 816 valores at√≠picos en la variable September 2015


price
October 2015
Q1:  1027.0
Q3:  1602.0
IQR:  575.0
BI:  164.5
BS:  2464.5
Hay 802 valores at√≠picos en la variable October 2015


price
November 2015
Q1:  1023.0
Q3:  1600.0
IQR:  577.0
BI:  157.5
BS:  2465.5
Hay 803 valores at√≠picos en la variable November 2015


price
December 2015
Q1:  1020.0
Q3:  1601.0
IQR:  581.0
BI:  148.5
BS:  2472.5
Hay 808 valores at√≠picos en la variable December 2015


price
January 2016
Q1:  1023.0
Q3:  1604.5
IQR:  581.5
BI:  150.75
BS:  2476.75
Hay 825 valores at√≠picos en la variable January 2016


price
February 2016
Q1:  1029.0
Q3:  1609.0
IQR:  580.0
BI:  159.0
BS:  2479.0
Hay 839 valores at√≠picos en la variable February 2016


price
March 2016
Q1:  1038.0
Q3:  1616.0
IQR:  578.0
BI:  171.0
BS:  2483.0
Hay 838 valores at√≠picos en la variable March 2016


price
April 2016
Q1:  1041.0
Q3:  1625.0
IQR:  584.0
BI:  165.0
BS:  2501.0
Hay 814 valores at√≠picos en la variable April 2016


price
May 2016
Q1:  1044.0
Q3:  1630.0
IQR:  586.0
BI:  165.0
BS:  2509.0
Hay 805 valores at√≠picos en la variable May 2016

c:\Users\Usuario\Desktop\2- Grupal\House_Market\Datasets\4- Zillow Rent Index\funcionesEDA.py:54: FutureWarning: The default dtype for empty Series will be 'object' instead of 'float64' in a future version. Specify a dtype explicitly to silence this warning.
  size = len(pd.Series(outliers).unique())

price
June 2016
Q1:  1046.0
Q3:  1633.0
IQR:  587.0
BI:  165.5
BS:  2513.5
Hay 806 valores at√≠picos en la variable June 2016


price
July 2016
Q1:  1043.5
Q3:  1629.0
IQR:  585.5
BI:  165.25
BS:  2507.25
Hay 817 valores at√≠picos en la variable July 2016


price
August 2016
Q1:  1038.0
Q3:  1628.0
IQR:  590.0
BI:  153.0
BS:  2513.0
Hay 810 valores at√≠picos en la variable August 2016


price
September 2016
Q1:  1034.0
Q3:  1628.0
IQR:  594.0
BI:  143.0
BS:  2519.0
Hay 804 valores at√≠picos en la variable September 2016


price
October 2016
Q1:  1032.0
Q3:  1630.5
IQR:  598.5
BI:  134.25
BS:  2528.25
Hay 789 valores at√≠picos en la variable October 2016


price
November 2016
Q1:  1033.0
Q3:  1630.0
IQR:  597.0
BI:  137.5
BS:  2525.5
Hay 796 valores at√≠picos en la variable November 2016


price
December 2016
Q1:  1034.0
Q3:  1632.0
IQR:  598.0
BI:  137.0
BS:  2529.0
Hay 794 valores at√≠picos en la variable December 2016


price
January 2017
Q1:  1035.0
Q3:  1634.0
IQR:  599.0
BI:  136.5
BS:  2532.5
Hay 791 valores at√≠picos en la variable January 2017


pricepersqft
City Code
Q1:  18762.0
Q3:  51298.5
IQR:  32536.5
BI:  -30042.75
BS:  100103.25
Hay 1874 valores at√≠picos en la variable City Code


pricepersqft
November 2010
Q1:  0.676
Q3:  0.972
IQR:  0.29599999999999993
BI:  0.23200000000000015
BS:  1.416
Hay 425 valores at√≠picos en la variable November 2010


pricepersqft
December 2010
Q1:  0.678
Q3:  0.974
IQR:  0.29599999999999993
BI:  0.23400000000000015
BS:  1.418
Hay 421 valores at√≠picos en la variable December 2010


pricepersqft
January 2011
Q1:  0.68
Q3:  0.976
IQR:  0.29599999999999993
BI:  0.23600000000000015
BS:  1.42
Hay 425 valores at√≠picos en la variable January 2011


pricepersqft
February 2011
Q1:  0.682
Q3:  0.972
IQR:  0.2899999999999999
BI:  0.24700000000000016
BS:  1.4069999999999998
Hay 453 valores at√≠picos en la variable February 2011


pricepersqft
March 2011
Q1:  0.68
Q3:  0.97
IQR:  0.2899999999999999
BI:  0.24500000000000016
BS:  1.4049999999999998
Hay 448 valores at√≠picos en la variable March 2011


pricepersqft
April 2011
Q1:  0.678
Q3:  0.968
IQR:  0.2899999999999999
BI:  0.24300000000000016
BS:  1.4029999999999998
Hay 446 valores at√≠picos en la variable April 2011


pricepersqft
May 2011
Q1:  0.678
Q3:  0.968
IQR:  0.2899999999999999
BI:  0.24300000000000016
BS:  1.4029999999999998
Hay 445 valores at√≠picos en la variable May 2011


pricepersqft
June 2011
Q1:  0.678
Q3:  0.968
IQR:  0.2899999999999999
BI:  0.24300000000000016
BS:  1.4029999999999998
Hay 437 valores at√≠picos en la variable June 2011


pricepersqft
July 2011
Q1:  0.678
Q3:  0.968
IQR:  0.2899999999999999
BI:  0.24300000000000016
BS:  1.4029999999999998
Hay 432 valores at√≠picos en la variable July 2011


pricepersqft
August 2011
Q1:  0.678
Q3:  0.966
IQR:  0.2879999999999999
BI:  0.24600000000000016
BS:  1.398
Hay 433 valores at√≠picos en la variable August 2011


pricepersqft
September 2011
Q1:  0.678
Q3:  0.964
IQR:  0.2859999999999999
BI:  0.24900000000000017
BS:  1.3929999999999998
Hay 441 valores at√≠picos en la variable September 2011


pricepersqft
October 2011
Q1:  0.676
Q3:  0.962
IQR:  0.2859999999999999
BI:  0.24700000000000016
BS:  1.3909999999999998
Hay 445 valores at√≠picos en la variable October 2011


pricepersqft
November 2011
Q1:  0.676
Q3:  0.962
IQR:  0.2859999999999999
BI:  0.24700000000000016
BS:  1.3909999999999998
Hay 450 valores at√≠picos en la variable November 2011


pricepersqft
December 2011
Q1:  0.676
Q3:  0.978
IQR:  0.30199999999999994
BI:  0.22300000000000014
BS:  1.4309999999999998
Hay 523 valores at√≠picos en la variable December 2011


pricepersqft
January 2012
Q1:  0.674
Q3:  0.978
IQR:  0.30399999999999994
BI:  0.21800000000000014
BS:  1.434
Hay 511 valores at√≠picos en la variable January 2012


pricepersqft
February 2012
Q1:  0.674
Q3:  0.978
IQR:  0.30399999999999994
BI:  0.21800000000000014
BS:  1.434
Hay 510 valores at√≠picos en la variable February 2012


pricepersqft
March 2012
Q1:  0.676
Q3:  0.98
IQR:  0.30399999999999994
BI:  0.22000000000000014
BS:  1.436
Hay 514 valores at√≠picos en la variable March 2012


pricepersqft
April 2012
Q1:  0.674
Q3:  0.974
IQR:  0.29999999999999993
BI:  0.22400000000000014
BS:  1.424
Hay 541 valores at√≠picos en la variable April 2012


pricepersqft
May 2012
Q1:  0.674
Q3:  0.976
IQR:  0.30199999999999994
BI:  0.22100000000000014
BS:  1.4289999999999998
Hay 541 valores at√≠picos en la variable May 2012


pricepersqft
June 2012
Q1:  0.674
Q3:  0.978
IQR:  0.30399999999999994
BI:  0.21800000000000014
BS:  1.434
Hay 537 valores at√≠picos en la variable June 2012


pricepersqft
July 2012
Q1:  0.672
Q3:  0.982
IQR:  0.30999999999999994
BI:  0.20700000000000013
BS:  1.4469999999999998
Hay 517 valores at√≠picos en la variable July 2012


pricepersqft
August 2012
Q1:  0.672
Q3:  0.98
IQR:  0.30799999999999994
BI:  0.21000000000000013
BS:  1.442
Hay 524 valores at√≠picos en la variable August 2012


pricepersqft
September 2012
Q1:  0.672
Q3:  0.98
IQR:  0.30799999999999994
BI:  0.21000000000000013
BS:  1.442
Hay 529 valores at√≠picos en la variable September 2012


pricepersqft
October 2012
Q1:  0.674
Q3:  0.98
IQR:  0.30599999999999994
BI:  0.21500000000000014
BS:  1.4389999999999998
Hay 532 valores at√≠picos en la variable October 2012


pricepersqft
November 2012
Q1:  0.676
Q3:  0.98
IQR:  0.30399999999999994
BI:  0.22000000000000014
BS:  1.436
Hay 542 valores at√≠picos en la variable November 2012


pricepersqft
December 2012
Q1:  0.676
Q3:  0.982
IQR:  0.30599999999999994
BI:  0.21700000000000014
BS:  1.4409999999999998
Hay 541 valores at√≠picos en la variable December 2012


pricepersqft
January 2013
Q1:  0.676
Q3:  0.984
IQR:  0.30799999999999994
BI:  0.21400000000000013
BS:  1.446
Hay 548 valores at√≠picos en la variable January 2013


pricepersqft
February 2013
Q1:  0.676
Q3:  0.986
IQR:  0.30999999999999994
BI:  0.21100000000000013
BS:  1.4509999999999998
Hay 553 valores at√≠picos en la variable February 2013


pricepersqft
March 2013
Q1:  0.676
Q3:  0.988
IQR:  0.31199999999999994
BI:  0.20800000000000013
BS:  1.456
Hay 549 valores at√≠picos en la variable March 2013


pricepersqft
April 2013
Q1:  0.676
Q3:  0.99
IQR:  0.31399999999999995
BI:  0.20500000000000013
BS:  1.4609999999999999
Hay 552 valores at√≠picos en la variable April 2013


pricepersqft
May 2013
Q1:  0.678
Q3:  0.99
IQR:  0.31199999999999994
BI:  0.21000000000000013
BS:  1.458
Hay 562 valores at√≠picos en la variable May 2013


pricepersqft
June 2013
Q1:  0.678
Q3:  0.992
IQR:  0.31399999999999995
BI:  0.20700000000000013
BS:  1.4629999999999999
Hay 562 valores at√≠picos en la variable June 2013


pricepersqft
July 2013
Q1:  0.68
Q3:  0.992
IQR:  0.31199999999999994
BI:  0.21200000000000013
BS:  1.46
Hay 568 valores at√≠picos en la variable July 2013


pricepersqft
August 2013
Q1:  0.681
Q3:  0.992
IQR:  0.31099999999999994
BI:  0.21450000000000014
BS:  1.4585
Hay 575 valores at√≠picos en la variable August 2013


pricepersqft
September 2013
Q1:  0.684
Q3:  0.994
IQR:  0.30999999999999994
BI:  0.21900000000000014
BS:  1.4589999999999999
Hay 582 valores at√≠picos en la variable September 2013


pricepersqft
October 2013
Q1:  0.688
Q3:  0.998
IQR:  0.31000000000000005
BI:  0.22299999999999986
BS:  1.463
Hay 585 valores at√≠picos en la variable October 2013


pricepersqft
November 2013
Q1:  0.692
Q3:  1.002
IQR:  0.31000000000000005
BI:  0.22699999999999987
BS:  1.467
Hay 581 valores at√≠picos en la variable November 2013


pricepersqft
December 2013
Q1:  0.694
Q3:  1.006
IQR:  0.31200000000000006
BI:  0.22599999999999987
BS:  1.4740000000000002
Hay 578 valores at√≠picos en la variable December 2013


pricepersqft
January 2014
Q1:  0.694
Q3:  1.004
IQR:  0.31000000000000005
BI:  0.22899999999999987
BS:  1.469
Hay 595 valores at√≠picos en la variable January 2014


pricepersqft
February 2014
Q1:  0.694
Q3:  1.002
IQR:  0.30800000000000005
BI:  0.23199999999999987
BS:  1.464
Hay 612 valores at√≠picos en la variable February 2014


pricepersqft
March 2014
Q1:  0.69
Q3:  1.0
IQR:  0.31000000000000005
BI:  0.22499999999999987
BS:  1.465
Hay 611 valores at√≠picos en la variable March 2014


pricepersqft
April 2014
Q1:  0.69
Q3:  0.998
IQR:  0.30800000000000005
BI:  0.22799999999999987
BS:  1.46
Hay 627 valores at√≠picos en la variable April 2014


pricepersqft
May 2014
Q1:  0.688
Q3:  0.995
IQR:  0.30700000000000005
BI:  0.22749999999999987
BS:  1.4555
Hay 636 valores at√≠picos en la variable May 2014


pricepersqft
June 2014
Q1:  0.686
Q3:  0.992
IQR:  0.30599999999999994
BI:  0.22700000000000015
BS:  1.4509999999999998
Hay 640 valores at√≠picos en la variable June 2014


pricepersqft
July 2014
Q1:  0.686
Q3:  0.994
IQR:  0.30799999999999994
BI:  0.22400000000000014
BS:  1.456
Hay 643 valores at√≠picos en la variable July 2014


pricepersqft
August 2014
Q1:  0.692
Q3:  1.0
IQR:  0.30800000000000005
BI:  0.22999999999999987
BS:  1.4620000000000002
Hay 645 valores at√≠picos en la variable August 2014


pricepersqft
September 2014
Q1:  0.696
Q3:  1.008
IQR:  0.31200000000000006
BI:  0.22799999999999987
BS:  1.476
Hay 640 valores at√≠picos en la variable September 2014


pricepersqft
October 2014
Q1:  0.7
Q3:  1.014
IQR:  0.31400000000000006
BI:  0.22899999999999987
BS:  1.485
Hay 652 valores at√≠picos en la variable October 2014


pricepersqft
November 2014
Q1:  0.704
Q3:  1.018
IQR:  0.31400000000000006
BI:  0.23299999999999987
BS:  1.489
Hay 671 valores at√≠picos en la variable November 2014


pricepersqft
December 2014
Q1:  0.706
Q3:  1.024
IQR:  0.31800000000000006
BI:  0.22899999999999987
BS:  1.5010000000000001
Hay 666 valores at√≠picos en la variable December 2014


pricepersqft
January 2015
Q1:  0.708
Q3:  1.03
IQR:  0.32200000000000006
BI:  0.22499999999999987
BS:  1.5130000000000001
Hay 653 valores at√≠picos en la variable January 2015


pricepersqft
February 2015
Q1:  0.71
Q3:  1.034
IQR:  0.32400000000000007
BI:  0.22399999999999987
BS:  1.52
Hay 649 valores at√≠picos en la variable February 2015


pricepersqft
March 2015
Q1:  0.712
Q3:  1.038
IQR:  0.32600000000000007
BI:  0.22299999999999986
BS:  1.5270000000000001
Hay 646 valores at√≠picos en la variable March 2015


pricepersqft
April 2015
Q1:  0.715
Q3:  1.04
IQR:  0.32500000000000007
BI:  0.22749999999999987
BS:  1.5275
Hay 653 valores at√≠picos en la variable April 2015


pricepersqft
May 2015
Q1:  0.718
Q3:  1.044
IQR:  0.32600000000000007
BI:  0.22899999999999987
BS:  1.5330000000000001
Hay 654 valores at√≠picos en la variable May 2015


pricepersqft
June 2015
Q1:  0.72
Q3:  1.048
IQR:  0.32800000000000007
BI:  0.22799999999999987
BS:  1.54
Hay 654 valores at√≠picos en la variable June 2015


pricepersqft
July 2015
Q1:  0.724
Q3:  1.052
IQR:  0.32800000000000007
BI:  0.23199999999999987
BS:  1.544
Hay 665 valores at√≠picos en la variable July 2015


pricepersqft
August 2015
Q1:  0.726
Q3:  1.056
IQR:  0.33000000000000007
BI:  0.23099999999999987
BS:  1.5510000000000002
Hay 661 valores at√≠picos en la variable August 2015


pricepersqft
September 2015
Q1:  0.726
Q3:  1.0550000000000002
IQR:  0.3290000000000002
BI:  0.2324999999999997
BS:  1.5485000000000004
Hay 666 valores at√≠picos en la variable September 2015


pricepersqft
October 2015
Q1:  0.724
Q3:  1.054
IQR:  0.33000000000000007
BI:  0.22899999999999987
BS:  1.5490000000000002
Hay 674 valores at√≠picos en la variable October 2015


pricepersqft
November 2015
Q1:  0.722
Q3:  1.054
IQR:  0.3320000000000001
BI:  0.22399999999999987
BS:  1.552
Hay 673 valores at√≠picos en la variable November 2015


pricepersqft
December 2015
Q1:  0.72
Q3:  1.054
IQR:  0.3340000000000001
BI:  0.21899999999999986
BS:  1.5550000000000002
Hay 672 valores at√≠picos en la variable December 2015


pricepersqft
January 2016
Q1:  0.722
Q3:  1.058
IQR:  0.3360000000000001
BI:  0.21799999999999986
BS:  1.5620000000000003
Hay 671 valores at√≠picos en la variable January 2016


pricepersqft
February 2016
Q1:  0.724
Q3:  1.06
IQR:  0.3360000000000001
BI:  0.21999999999999986
BS:  1.564
Hay 675 valores at√≠picos en la variable February 2016


pricepersqft
March 2016
Q1:  0.728
Q3:  1.066
IQR:  0.3380000000000001
BI:  0.22099999999999986
BS:  1.5730000000000002
Hay 679 valores at√≠picos en la variable March 2016


pricepersqft
April 2016
Q1:  0.732
Q3:  1.072
IQR:  0.3400000000000001
BI:  0.22199999999999986
BS:  1.5820000000000003
Hay 670 valores at√≠picos en la variable April 2016


pricepersqft
May 2016
Q1:  0.734
Q3:  1.076
IQR:  0.3420000000000001
BI:  0.22099999999999986
BS:  1.5890000000000002
Hay 671 valores at√≠picos en la variable May 2016


pricepersqft
June 2016
Q1:  0.734
Q3:  1.08
IQR:  0.3460000000000001
BI:  0.21499999999999986
BS:  1.5990000000000002
Hay 666 valores at√≠picos en la variable June 2016


pricepersqft
July 2016
Q1:  0.732
Q3:  1.082
IQR:  0.3500000000000001
BI:  0.20699999999999985
BS:  1.6070000000000002
Hay 656 valores at√≠picos en la variable July 2016


pricepersqft
August 2016
Q1:  0.73
Q3:  1.08
IQR:  0.3500000000000001
BI:  0.20499999999999985
BS:  1.6050000000000002
Hay 666 valores at√≠picos en la variable August 2016


pricepersqft
September 2016
Q1:  0.728
Q3:  1.08
IQR:  0.3520000000000001
BI:  0.19999999999999984
BS:  1.608
Hay 661 valores at√≠picos en la variable September 2016


pricepersqft
October 2016
Q1:  0.728
Q3:  1.082
IQR:  0.3540000000000001
BI:  0.19699999999999984
BS:  1.6130000000000002
Hay 653 valores at√≠picos en la variable October 2016


pricepersqft
November 2016
Q1:  0.728
Q3:  1.082
IQR:  0.3540000000000001
BI:  0.19699999999999984
BS:  1.6130000000000002
Hay 660 valores at√≠picos en la variable November 2016


pricepersqft
December 2016
Q1:  0.73
Q3:  1.08
IQR:  0.3500000000000001
BI:  0.20499999999999985
BS:  1.6050000000000002
Hay 671 valores at√≠picos en la variable December 2016


pricepersqft
January 2017
Q1:  0.732
Q3:  1.08
IQR:  0.3480000000000001
BI:  0.20999999999999985
BS:  1.6020000000000003
Hay 680 valores at√≠picos en la variable January 2017